### ISSUE TITLE
Add Import/Export feature

### ISSUE THREAD

**Issue by charliehuizenga** [Agua-Para-La-Vida/air-in-pipes#1]
These buttons could be on the Principal page or possibly on the Menu bar.

Import:

Bring up a File Open dialog that allows user to select a file on their computer
Load the file including: Project Info, Profile Data, Results

Export:

Bring up a File SaveAs dialog that allows user to select a location and filename on their computer
Save the json file (including: Project Info, Profile Data, Results)

**Comment by mario-gonzalezvarg** [comment]
Both import/export feature logic are implemented
