### ISSUE TITLE
Add Example design data to interface

### ISSUE THREAD

**Issue by charliehuizenga** [Agua-Para-La-Vida/air-in-pipes#3]
Add "Load Example" button to interface which will give user a list of example files:
Example 1
Example 2
Example 3
Example 4
Example 5
Example 6
Example 7

Selecting one of these will load the data from a predefined example json data structure in the code, enabling the user to run one of the example files in the Air In Pipes manual

**Comment by mario-gonzalezvarg** [comment]
I've uploaded the example JSON files provided in the Google Drive

**Comment by mario-gonzalezvarg** [comment]
Need to implement again
